[package]
name = "flyg-format"
description = "The Rust implementation for the Flyg file format"
authors = ["Tim Janke <tim+github@janke.biz>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
